### PR TITLE
Update ap.py

### PR DESCRIPTION
**Pull request by songweige**
Hi Jerry,

I met AssertionError when running lambdamart with Z = MAP. Then I check the calculation on swap_deltas. And I found that there might be a mistake in your algorithm which caused the error. Maybe you can check it by use some examples.

Cheers

### CODE REVIEW

**Comment by songweige** [comment]
i.e. The denominator of MAP should be the total number of relevant documents instead of the number of relevant document before truncation. Otherwise, for example, we have document list(1, 0, 0, 0, 0, 0, 1). If we swap i=5 and i=7, then the MAP@5 will reduce from 1 to 0.7.

**Comment by jma127** [comment]
Hi Songwei, it looks like you are correct. Thanks for catching this!

**Comment by jma127** [comment]
Tests are failing due to one test case ``[1, 0, 1, 0, 1]``, fixing now.

**Comment by songweige** [comment]
You're welcomeXD

**Comment by songweige** [comment]
Got it. Thanks for your codes, too. They are really helpful.

**Comment by jma127** [comment]
So glad you find it useful :).

On Jun 29, 2017 09:58, "SongweiGe" <notifications@github.com> wrote:

Got it. Thanks for your codes, too. They are really helpful.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/jma127/pyltr/pull/6#issuecomment-311974914>, or mute
the thread

**Pull request merged**
